"""baseline schema — extensions, enums, and all core tables

Hand-written (not autogenerated) so it matches docs/TECHNICAL_SPEC.md §2 exactly —
computed columns and enum arrays aren't reliably round-tripped by Alembic's
autogenerate, so this migration is the source of truth and app/models/* mirror it
for the ORM layer.

Revision ID: 0001
Revises:
Create Date: 2026-08-17
"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext"')

    op.execute(
        """
        CREATE TYPE user_role AS ENUM (
          'super_admin', 'admin', 'agent', 'billing', 'tl',
          'auditor', 'cs', 'change_dep', 'chargeback_dep', 'cr_booking'
        )
        """
    )
    op.execute("CREATE TYPE service_type AS ENUM ('car', 'hotel', 'flight')")
    op.execute(
        """
        CREATE TYPE booking_status AS ENUM (
          'authorization_pending', 'client_approved', 'transferred_to_billing',
          'card_charged', 'card_declined', 'tag_change_dep', 'tag_cr_booking',
          'tag_auditor', 'qc_done', 'tag_refund', 'tag_rdr', 'tag_chargeback'
        )
        """
    )
    op.execute("CREATE TYPE pii_field AS ENUM ('email', 'phone', 'card')")
    op.execute("CREATE TYPE sync_status AS ENUM ('pending', 'success', 'failed')")
    op.execute("CREATE TYPE transmission_type AS ENUM ('automatic', 'manual')")
    op.execute(
        """
        CREATE TYPE vehicle_type AS ENUM (
          'economy', 'compact', 'intermediate', 'standard', 'full_size',
          'standard_suv', 'intermediate_suv', 'premium_suv', 'full_size_suv',
          'luxury', 'passenger_van', 'mini_van', 'fifteen_passenger_van',
          'mystery_car', 'premium_crossover', 'premium_elite_crossover',
          'pickup_truck', 'electric'
        )
        """
    )

    op.execute(
        """
        CREATE TABLE users (
          id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          name             TEXT NOT NULL,
          email            CITEXT UNIQUE NOT NULL,
          password_hash    TEXT NOT NULL,
          role             user_role NOT NULL,
          ip_whitelist_enabled BOOLEAN NOT NULL DEFAULT FALSE,
          is_active        BOOLEAN NOT NULL DEFAULT TRUE,
          created_by       UUID REFERENCES users(id),
          created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE user_whitelisted_ips (
          id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          ip_address  INET NOT NULL,
          label       TEXT,
          created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
          UNIQUE (user_id, ip_address)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE system_settings (
          id                       BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id),
          registration_enabled     BOOLEAN NOT NULL DEFAULT FALSE,
          updated_by               UUID REFERENCES users(id),
          updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE leads (
          id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          name             TEXT NOT NULL,
          phone            TEXT NOT NULL,
          email            CITEXT NOT NULL,
          service_type     service_type,
          status           booking_status NOT NULL DEFAULT 'authorization_pending',
          agent_id         UUID NOT NULL REFERENCES users(id),
          is_duplicate     BOOLEAN NOT NULL DEFAULT FALSE,
          duplicate_of_id  UUID REFERENCES leads(id),
          duplicate_override_reason TEXT,
          created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_leads_agent_id ON leads(agent_id)")
    op.execute("CREATE INDEX idx_leads_status ON leads(status)")
    op.execute("CREATE INDEX idx_leads_email ON leads(email)")
    op.execute("CREATE INDEX idx_leads_phone ON leads(phone)")
    op.execute("CREATE INDEX idx_leads_name_trgm ON leads USING gin (name gin_trgm_ops)")

    op.execute(
        """
        CREATE TABLE lead_access_grants (
          id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id     UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          granted_by  UUID NOT NULL REFERENCES users(id),
          created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_lead_access_grants_lead ON lead_access_grants(lead_id)")

    op.execute(
        """
        CREATE TABLE car_bookings (
          id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id             UUID NOT NULL UNIQUE REFERENCES leads(id) ON DELETE CASCADE,
          booking_reference   TEXT NOT NULL,
          booking_platform    TEXT NOT NULL,
          car_provider        TEXT NOT NULL,
          renter_name         TEXT NOT NULL,
          renter_dob          DATE NOT NULL,
          transmission        transmission_type NOT NULL,
          fuel_policy         TEXT,
          vehicle_type        vehicle_type NOT NULL,
          pickup_datetime     TIMESTAMPTZ NOT NULL,
          pickup_location     TEXT NOT NULL,
          return_datetime     TIMESTAMPTZ NOT NULL,
          return_location     TEXT NOT NULL,
          prepaid_amount      NUMERIC(12,2) NOT NULL DEFAULT 0,
          pay_at_counter_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
          total_amount        NUMERIC(12,2) GENERATED ALWAYS AS (prepaid_amount + pay_at_counter_amount) STORED,
          created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE hotel_bookings (
          id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id             UUID NOT NULL UNIQUE REFERENCES leads(id) ON DELETE CASCADE,
          booking_reference   TEXT NOT NULL,
          booking_platform    TEXT NOT NULL,
          hotel_name          TEXT NOT NULL,
          room_type           TEXT NOT NULL,
          location             TEXT NOT NULL,
          check_in_date       DATE NOT NULL,
          check_out_date      DATE NOT NULL,
          prepaid_amount      NUMERIC(12,2) NOT NULL DEFAULT 0,
          pay_at_counter_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
          total_amount        NUMERIC(12,2) GENERATED ALWAYS AS (prepaid_amount + pay_at_counter_amount) STORED,
          created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
          CHECK (check_out_date > check_in_date)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE flight_bookings (
          id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id             UUID NOT NULL UNIQUE REFERENCES leads(id) ON DELETE CASCADE,
          booking_reference   TEXT NOT NULL,
          pnr                 TEXT NOT NULL,
          airline             TEXT NOT NULL,
          flight_numbers      TEXT[] NOT NULL,
          origin              TEXT NOT NULL,
          destination         TEXT NOT NULL,
          cabin_class         TEXT NOT NULL,
          prepaid_amount      NUMERIC(12,2) NOT NULL DEFAULT 0,
          pay_at_counter_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
          total_amount        NUMERIC(12,2) GENERATED ALWAYS AS (prepaid_amount + pay_at_counter_amount) STORED,
          created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE booking_modifications (
          id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id             UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          field_name          TEXT NOT NULL,
          original_value      JSONB NOT NULL,
          revised_value       JSONB NOT NULL,
          modification_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
          modified_by         UUID NOT NULL REFERENCES users(id),
          created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_booking_mods_lead ON booking_modifications(lead_id)")

    op.execute(
        """
        CREATE TABLE cancellations (
          id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id                UUID NOT NULL UNIQUE REFERENCES leads(id) ON DELETE CASCADE,
          original_prepaid_amount NUMERIC(12,2) NOT NULL,
          cancellation_penalty_fee NUMERIC(12,2) NOT NULL DEFAULT 0,
          refund_amount          NUMERIC(12,2) GENERATED ALWAYS AS
                                   (GREATEST(original_prepaid_amount - cancellation_penalty_fee, 0)) STORED,
          final_retained_amount  NUMERIC(12,2) GENERATED ALWAYS AS
                                   (LEAST(cancellation_penalty_fee, original_prepaid_amount)) STORED,
          cancelled_by           UUID NOT NULL REFERENCES users(id),
          created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE payment_transactions (
          id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id        UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          prepaid_amount NUMERIC(12,2) NOT NULL,
          pay_at_counter_amount NUMERIC(12,2) NOT NULL,
          total_amount   NUMERIC(12,2) GENERATED ALWAYS AS (prepaid_amount + pay_at_counter_amount) STORED,
          card_last_four TEXT,
          card_token     TEXT,
          outcome        TEXT NOT NULL DEFAULT 'pending',
          processed_by   UUID REFERENCES users(id),
          processed_at   TIMESTAMPTZ,
          created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_payments_lead ON payment_transactions(lead_id)")

    op.execute(
        """
        CREATE TABLE future_credits (
          id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          source_lead_id   UUID NOT NULL REFERENCES leads(id),
          voucher_amount   NUMERIC(12,2) NOT NULL,
          number_of_vouchers INTEGER NOT NULL DEFAULT 1,
          validity_date    DATE NOT NULL,
          created_by       UUID NOT NULL REFERENCES users(id),
          created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_future_credits_source ON future_credits(source_lead_id)")

    op.execute(
        """
        CREATE TABLE authorization_records (
          id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id               UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          cardholder_confirmed  BOOLEAN NOT NULL,
          prepaid_charge_ack    BOOLEAN NOT NULL,
          pay_at_counter_ack    BOOLEAN NOT NULL,
          booking_details_ack   BOOLEAN NOT NULL,
          terms_ack             BOOLEAN NOT NULL,
          non_refundable_ack    BOOLEAN NOT NULL,
          consent_status        TEXT NOT NULL DEFAULT 'authorized',
          customer_ip           INET NOT NULL,
          user_agent            TEXT NOT NULL,
          authorized_at         TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_auth_records_lead ON authorization_records(lead_id)")

    op.execute(
        """
        CREATE TABLE status_lookup (
          status         booking_status PRIMARY KEY,
          label          TEXT NOT NULL,
          ui_color       TEXT NOT NULL,
          set_by_roles   user_role[] NOT NULL,
          notifies_roles user_role[] NOT NULL,
          sort_order     INTEGER NOT NULL
        )
        """
    )

    op.execute(
        """
        CREATE TABLE status_history (
          id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id      UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          from_status  booking_status,
          to_status    booking_status NOT NULL,
          changed_by   UUID NOT NULL REFERENCES users(id),
          changed_at   TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_status_history_lead ON status_history(lead_id)")

    op.execute(
        """
        CREATE TABLE notifications (
          id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id         UUID REFERENCES leads(id) ON DELETE CASCADE,
          recipient_user_id UUID REFERENCES users(id),
          recipient_role  user_role,
          type            TEXT NOT NULL,
          message         TEXT NOT NULL,
          is_read         BOOLEAN NOT NULL DEFAULT FALSE,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_notifications_recipient ON notifications(recipient_user_id, is_read)")

    op.execute(
        """
        CREATE TABLE access_notification_log (
          id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id      UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          opened_by    UUID NOT NULL REFERENCES users(id),
          opened_at    TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_access_log_lead ON access_notification_log(lead_id)")

    op.execute(
        """
        CREATE TABLE pii_reveal_audit_log (
          id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id        UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          agent_id       UUID NOT NULL REFERENCES users(id),
          field_revealed pii_field NOT NULL,
          reason         TEXT NOT NULL,
          ip_address     INET NOT NULL,
          user_agent     TEXT NOT NULL,
          revealed_at    TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_pii_log_lead ON pii_reveal_audit_log(lead_id)")

    op.execute(
        """
        CREATE TABLE booking_process_log (
          id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id       UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          actor_id      UUID NOT NULL REFERENCES users(id),
          action        TEXT NOT NULL,
          field_changed TEXT,
          old_value     JSONB,
          new_value     JSONB,
          created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_process_log_lead ON booking_process_log(lead_id)")
    # NOTE: this table should become insert-only for the app's runtime DB role
    # (REVOKE UPDATE, DELETE ...) once a non-owner app role exists — see Phase 7
    # in TECHNICAL_SPEC.md §10. Skipped here because the Phase 0 dev role owns
    # the schema, and revoking from the owner has no effect.

    op.execute(
        """
        CREATE TABLE google_sheets_sync_status (
          id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          lead_id      UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          table_name   TEXT NOT NULL DEFAULT 'leads',
          status       sync_status NOT NULL DEFAULT 'pending',
          attempts     INTEGER NOT NULL DEFAULT 0,
          last_error   TEXT,
          synced_at    TIMESTAMPTZ,
          created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_sheets_sync_status ON google_sheets_sync_status(status)")

    # Seed status_lookup — mirrors TECHNICAL_SPEC.md §3 / PRD §6.1 (colors are the PRD's UI Colour column).
    op.execute(
        """
        INSERT INTO status_lookup (status, label, ui_color, set_by_roles, notifies_roles, sort_order) VALUES
        ('authorization_pending', 'Authorization Pending', 'grey', '{}', '{}', 1),
        ('client_approved', 'Client Approved', 'blue', '{}', '{admin}', 2),
        ('transferred_to_billing', 'Transferred to Billing', 'purple', '{agent,super_admin,admin}', '{billing}', 3),
        ('card_charged', 'Card Charged', 'green', '{billing}', '{agent}', 4),
        ('card_declined', 'Card Declined', 'red', '{billing}', '{agent}', 5),
        ('tag_change_dep', 'Tag to Change Dep', 'yellow', '{}', '{change_dep}', 6),
        ('tag_cr_booking', 'Tag to CR Booking', 'orange', '{}', '{cr_booking}', 7),
        ('tag_auditor', 'Tag to Auditor', 'cyan', '{}', '{auditor,admin}', 8),
        ('qc_done', 'QC Done', 'dark_green', '{auditor}', '{agent,admin}', 9),
        ('tag_refund', 'Tag Refund', 'red', '{billing}', '{billing}', 10),
        ('tag_rdr', 'Tag RDR', 'black', '{billing}', '{billing,chargeback_dep}', 11),
        ('tag_chargeback', 'Tag Chargeback', 'black', '{billing}', '{billing,chargeback_dep}', 12)
        """
    )


def downgrade() -> None:
    for table in [
        "google_sheets_sync_status",
        "booking_process_log",
        "pii_reveal_audit_log",
        "access_notification_log",
        "notifications",
        "status_history",
        "status_lookup",
        "authorization_records",
        "future_credits",
        "payment_transactions",
        "cancellations",
        "booking_modifications",
        "flight_bookings",
        "hotel_bookings",
        "car_bookings",
        "lead_access_grants",
        "leads",
        "system_settings",
        "user_whitelisted_ips",
        "users",
    ]:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")

    for enum_type in [
        "vehicle_type",
        "transmission_type",
        "sync_status",
        "pii_field",
        "booking_status",
        "service_type",
        "user_role",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_type}")
