"""Roles & Permissions engine — replaces the fixed `user_role` Postgres enum
with data-driven `roles`/`permissions`/`role_permissions` tables, so an admin
can create new roles and grant them permission combinations at runtime
without a deploy (Master Admin feature).

This is a like-for-like migration, not a permission reset: every one of the
10 existing roles is seeded with exactly the permission set it already has
today, reverse-engineered 1:1 from the hardcoded role-tuple constants this
replaces (deps.py, dashboard.py, leads.py, bookings.py, modifications.py,
cancellations.py, future_credits.py, audit.py, integrations.py, payments.py,
users.py) — see app/domain/permissions.py for the canonical catalog this
seed data mirrors, same "hand-written, not autogenerated" convention this
repo already uses for enums (0001's docstring).

`status_lookup.set_by_roles`/`notifies_roles` (ARRAY(user_role) columns,
unused scaffolding from Phase 0 — see status_machine.py's TRANSITIONS dict,
which is what's actually live) are dropped here too, since they reference
the `user_role` type this migration drops. Their real replacement — a proper
`status_role_permissions` join table — lands in migration 0007, which also
switches status_machine.py's role-gating from Python to that table.

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-19
"""
from alembic import op

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None

# (code, description, category)
PERMISSIONS = [
    ("leads.view_all", "View all leads", "Leads"),
    ("leads.view_own", "View own assigned leads", "Leads"),
    ("leads.create", "Create leads and bookings", "Leads"),
    ("billing.charge_card", "Process card charges and declines", "Billing"),
    ("dashboard.qc_stats", "View QC queue stats on the dashboard", "Dashboard"),
    ("dashboard.billing_stats", "View billing queue stats on the dashboard", "Dashboard"),
    ("dashboard.revenue_stats", "View company-wide revenue on the dashboard", "Dashboard"),
    ("dashboard.system_stats", "View system-wide stats (users, integrations)", "Dashboard"),
    ("modifications.manage", "Record and view booking modifications", "Modifications"),
    ("cancellations.manage", "Cancel bookings", "Cancellations"),
    ("future_credits.create", "Issue future credits", "Future Credits"),
    ("future_credits.view", "View the future credits ledger", "Future Credits"),
    ("audit.view", "View process/PII/access audit logs", "Audit"),
    ("integrations.manage", "Manage external integration API keys", "Integrations"),
    ("admin.manage_users", "Create and edit users", "Admin"),
    ("admin.view_settings", "View system settings", "Admin"),
    ("admin.manage_settings", "Edit system settings", "Admin"),
    ("admin.manage_roles", "Create/edit roles and permissions", "Admin"),
    ("admin.manage_custom_fields", "Define custom form fields", "Admin"),
    ("admin.view_activity_log", "View the activity log", "Admin"),
]

# The 10 existing role names, unchanged.
ROLE_NAMES = [
    "super_admin",
    "admin",
    "agent",
    "billing",
    "tl",
    "auditor",
    "cs",
    "change_dep",
    "chargeback_dep",
    "cr_booking",
]

# role_name -> [permission codes], reverse-engineered 1:1 from today's
# hardcoded constants (see the migration docstring for the file list).
ROLE_PERMISSIONS: dict[str, list[str]] = {
    "super_admin": [code for code, _, _ in PERMISSIONS],  # everything
    "admin": [
        "leads.view_all",
        "leads.create",
        "dashboard.qc_stats",
        "dashboard.billing_stats",
        "dashboard.revenue_stats",
        "dashboard.system_stats",
        "modifications.manage",
        "cancellations.manage",
        "future_credits.create",
        "future_credits.view",
        "audit.view",
        "integrations.manage",
        "admin.manage_users",
        "admin.view_settings",
        "admin.manage_custom_fields",
        "admin.view_activity_log",
    ],
    "agent": ["leads.view_own", "leads.create"],
    "billing": ["billing.charge_card", "dashboard.billing_stats", "future_credits.view"],
    "tl": [
        "leads.view_all",
        "dashboard.qc_stats",
        "dashboard.billing_stats",
        "dashboard.revenue_stats",
        "future_credits.create",
        "future_credits.view",
    ],
    "auditor": ["dashboard.qc_stats", "future_credits.view"],
    "cs": ["modifications.manage", "cancellations.manage", "future_credits.create", "future_credits.view"],
    "change_dep": ["modifications.manage", "cancellations.manage", "future_credits.view"],
    "chargeback_dep": ["future_credits.view"],
    "cr_booking": [],  # only ever had status-based lead visibility (task 0007), never a flat permission
}


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE permissions (
          id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          code         TEXT UNIQUE NOT NULL,
          description  TEXT NOT NULL,
          category     TEXT NOT NULL,
          created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE roles (
          id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          name            TEXT UNIQUE NOT NULL,
          is_system_role  BOOLEAN NOT NULL DEFAULT FALSE,
          created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE role_permissions (
          role_id        UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
          permission_id  UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
          PRIMARY KEY (role_id, permission_id)
        )
        """
    )

    for code, description, category in PERMISSIONS:
        op.execute(
            "INSERT INTO permissions (code, description, category) VALUES "
            f"({_q(code)}, {_q(description)}, {_q(category)})"
        )

    for name in ROLE_NAMES:
        op.execute(f"INSERT INTO roles (name, is_system_role) VALUES ({_q(name)}, TRUE)")

    for role_name, codes in ROLE_PERMISSIONS.items():
        for code in codes:
            op.execute(
                f"""
                INSERT INTO role_permissions (role_id, permission_id)
                SELECT r.id, p.id FROM roles r, permissions p
                WHERE r.name = {_q(role_name)} AND p.code = {_q(code)}
                """
            )

    # users.role (enum) -> users.role_id (FK), backfilled by matching name.
    op.execute("ALTER TABLE users ADD COLUMN role_id UUID REFERENCES roles(id)")
    op.execute("UPDATE users SET role_id = (SELECT id FROM roles WHERE roles.name = users.role::text)")
    op.execute("ALTER TABLE users ALTER COLUMN role_id SET NOT NULL")
    op.execute("ALTER TABLE users DROP COLUMN role")

    # notifications.recipient_role (enum) -> notifications.recipient_role_id (FK).
    op.execute("ALTER TABLE notifications ADD COLUMN recipient_role_id UUID REFERENCES roles(id)")
    op.execute(
        """
        UPDATE notifications SET recipient_role_id = (SELECT id FROM roles WHERE roles.name = notifications.recipient_role::text)
        WHERE recipient_role IS NOT NULL
        """
    )
    op.execute("ALTER TABLE notifications DROP COLUMN recipient_role")

    # Unused Phase-0 scaffolding referencing the enum type — see docstring.
    # Replaced by a proper status_role_permissions join table in 0007.
    op.execute("ALTER TABLE status_lookup DROP COLUMN set_by_roles")
    op.execute("ALTER TABLE status_lookup DROP COLUMN notifies_roles")

    op.execute("DROP TYPE user_role")


def _q(value: str) -> str:
    """Minimal SQL string literal quoting for this migration's static, trusted
    seed data (no user input reaches this function)."""
    return "'" + value.replace("'", "''") + "'"


def downgrade() -> None:
    op.execute("ALTER TABLE status_lookup ADD COLUMN set_by_roles TEXT[]")
    op.execute("ALTER TABLE status_lookup ADD COLUMN notifies_roles TEXT[]")

    op.execute(
        """
        CREATE TYPE user_role AS ENUM (
          'super_admin', 'admin', 'agent', 'billing', 'tl',
          'auditor', 'cs', 'change_dep', 'chargeback_dep', 'cr_booking'
        )
        """
    )

    op.execute("ALTER TABLE notifications ADD COLUMN recipient_role user_role")
    op.execute(
        """
        UPDATE notifications SET recipient_role = (SELECT name FROM roles WHERE roles.id = notifications.recipient_role_id)::user_role
        WHERE recipient_role_id IS NOT NULL
        """
    )
    op.execute("ALTER TABLE notifications DROP COLUMN recipient_role_id")

    op.execute("ALTER TABLE users ADD COLUMN role user_role")
    op.execute("UPDATE users SET role = (SELECT name FROM roles WHERE roles.id = users.role_id)::user_role")
    op.execute("ALTER TABLE users ALTER COLUMN role SET NOT NULL")
    op.execute("ALTER TABLE users DROP COLUMN role_id")

    op.execute("DROP TABLE IF EXISTS role_permissions")
    op.execute("DROP TABLE IF EXISTS roles")
    op.execute("DROP TABLE IF EXISTS permissions")
