"""Canonical permission catalog — the reference this repo's seed migration
(0006_roles_permissions.py) mirrors exactly, same "hand-written, not
autogenerated" convention already used for enum seed data (see 0001's
docstring). Keep these two in sync by hand; there's no runtime coupling
between them (the migration's copy is what actually ends up in the
`permissions` table — this is the documentation-facing source new code
should reference by name instead of typing raw strings).
"""
from dataclasses import dataclass


@dataclass(frozen=True)
class PermissionDef:
    code: str
    description: str
    category: str


PERMISSION_CATALOG: list[PermissionDef] = [
    PermissionDef("leads.view_all", "View all leads", "Leads"),
    PermissionDef("leads.view_own", "View own assigned leads", "Leads"),
    PermissionDef("leads.create", "Create leads and bookings", "Leads"),
    PermissionDef("billing.charge_card", "Process card charges and declines", "Billing"),
    PermissionDef("dashboard.qc_stats", "View QC queue stats on the dashboard", "Dashboard"),
    PermissionDef("dashboard.billing_stats", "View billing queue stats on the dashboard", "Dashboard"),
    PermissionDef("dashboard.revenue_stats", "View company-wide revenue on the dashboard", "Dashboard"),
    PermissionDef("dashboard.system_stats", "View system-wide stats (users, integrations)", "Dashboard"),
    PermissionDef("modifications.manage", "Record and view booking modifications", "Modifications"),
    PermissionDef("cancellations.manage", "Cancel bookings", "Cancellations"),
    PermissionDef("future_credits.create", "Issue future credits", "Future Credits"),
    PermissionDef("future_credits.view", "View the future credits ledger", "Future Credits"),
    PermissionDef("audit.view", "View process/PII/access audit logs", "Audit"),
    PermissionDef("integrations.manage", "Manage external integration API keys", "Integrations"),
    PermissionDef("admin.manage_users", "Create and edit users", "Admin"),
    PermissionDef("admin.view_settings", "View system settings", "Admin"),
    PermissionDef("admin.manage_settings", "Edit system settings", "Admin"),
    PermissionDef("admin.manage_roles", "Create/edit roles and permissions", "Admin"),
    PermissionDef("admin.manage_custom_fields", "Define custom form fields", "Admin"),
    PermissionDef("admin.view_activity_log", "View the activity log", "Admin"),
]

PERMISSION_CODES = {p.code for p in PERMISSION_CATALOG}
